[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
test = [
    "pytest>=8.3.5",
]
